
col_rename_dict_vol = {'Vehicle Type':"vehicle_type",
                'Zone ID':"zone_id",
                'Zone Name': "zone_name",
                'Zone Is Pass-Through': "zone_is_pass_through",
                'Zone is Bi-Direction': "zone_is_bidirectional",
                'Day Type': "day_type",
                'Day Part': "day_part",
                'Average Daily Segment Traffic (StL Volume)':"seg_traffic_stl_vol",
                'Avg Segment Speed (mph)': "mean_seg_speed_mph",
                'Avg All Segment Speed (mph)': "mean_all_seg_speed_mph",
                'Avg Segment Duration (sec)': "mean_seg_duration_sec",
                'Avg All Segment Duration (sec)': "mean_all_seg_duration_sec",
                'Free Flow Factor': "free_flow_factor",
                'Segment Speed 0-10 mph (percent)': "seg_speed_0_10_mph_pct",
                'Segment Speed 10-20 mph (percent)': "seg_speed_10_20_mph_pct",
                'Segment Speed 20-30 mph (percent)': "seg_speed_20_30_mph_pct",
                'Segment Speed 30-40 mph (percent)': "seg_speed_30_40_mph_pct",
                'Segment Speed 40-50 mph (percent)':"seg_speed_40_50_mph_pct",
                'Segment Speed 50-60 mph (percent)':"seg_speed_50_60_mph_pct",
                'Segment Speed 60-70 mph (percent)':"seg_speed_60_70_mph_pct",
                'Segment Speed 70-80 mph (percent)':"seg_speed_70_80_mph_pct",
                'Segment Speed 80-90 mph (percent)':"seg_speed_80_90_mph_pct",
                'Segment Speed 90+ mph (percent)':"seg_speed_90_plus_mph_pct",
                'Segment Duration 0-10 min (percent)':"seg_duration_0_10_min_pct",
                'Segment Duration 10-20 min (percent)':"seg_duration_10_20_min_pct",
                'Segment Duration 20-30 min (percent)':"seg_duration_20_30_min_pct",
                'Segment Duration 30-40 min (percent)':"seg_duration_30_40_min_pct",
                'Segment Duration 40-50 min (percent)':"seg_duration_40_50_min_pct",
                'Segment Duration 50-60 min (percent)':"seg_duration_50_60_min_pct",
                'Segment Duration 60-70 min (percent)':"seg_duration_60_70_min_pct",
                'Segment Duration 70-80 min (percent)':"seg_duration_70_80_min_pct",
                'Segment Duration 80-90 min (percent)':"seg_duration_80_90_min_pct",
                'Segment Duration 90-100 min (percent)':"seg_duration_90_100_min_pct",
                'Segment Duration 100-110 min (percent)':"seg_duration_100_110_min_pct",
                'Segment Duration 110-120 min (percent)':"seg_duration_110_120_min_pct",
                'Segment Duration 120-130 min (percent)':"seg_duration_120_130_min_pct",
                'Segment Duration 130-140 min (percent)':"seg_duration_130_140_min_pct",
                'Segment Duration 140-150 min (percent)':"seg_duration_140_150_min_pct",
                'Segment Duration 150+ min (percent)':"seg_duration_150_plus_min_pct"
            }

col_rename_dict_idx = {'Vehicle Type':"vehicle_type",
                'Zone ID':"zone_id",
                'Zone Name': "zone_name",
                'Zone Is Pass-Through': "zone_is_pass_through",
                'Zone is Bi-Direction': "zone_is_bidirectional",
                'Day Type': "day_type",
                'Day Part': "day_part",
                'Average Daily Segment Traffic (StL Index)':"seg_traffic_stl_index",
                'Avg Segment Speed (mph)': "mean_seg_speed_mph",
                'Avg All Segment Speed (mph)': "mean_all_seg_speed_mph",
                'Avg Segment Duration (sec)': "mean_seg_duration_sec",
                'Avg All Segment Duration (sec)': "mean_all_seg_duration_sec",
                'Free Flow Factor': "free_flow_factor",
                'Segment Speed 0-10 mph (percent)': "seg_speed_0_10_mph_pct",
                'Segment Speed 10-20 mph (percent)': "seg_speed_10_20_mph_pct",
                'Segment Speed 20-30 mph (percent)': "seg_speed_20_30_mph_pct",
                'Segment Speed 30-40 mph (percent)': "seg_speed_30_40_mph_pct",
                'Segment Speed 40-50 mph (percent)':"seg_speed_40_50_mph_pct",
                'Segment Speed 50-60 mph (percent)':"seg_speed_50_60_mph_pct",
                'Segment Speed 60-70 mph (percent)':"seg_speed_60_70_mph_pct",
                'Segment Speed 70-80 mph (percent)':"seg_speed_70_80_mph_pct",
                'Segment Speed 80-90 mph (percent)':"seg_speed_80_90_mph_pct",
                'Segment Speed 90+ mph (percent)':"seg_speed_90_plus_mph_pct",
                'Segment Duration 0-10 min (percent)':"seg_duration_0_10_min_pct",
                'Segment Duration 10-20 min (percent)':"seg_duration_10_20_min_pct",
                'Segment Duration 20-30 min (percent)':"seg_duration_20_30_min_pct",
                'Segment Duration 30-40 min (percent)':"seg_duration_30_40_min_pct",
                'Segment Duration 40-50 min (percent)':"seg_duration_40_50_min_pct",
                'Segment Duration 50-60 min (percent)':"seg_duration_50_60_min_pct",
                'Segment Duration 60-70 min (percent)':"seg_duration_60_70_min_pct",
                'Segment Duration 70-80 min (percent)':"seg_duration_70_80_min_pct",
                'Segment Duration 80-90 min (percent)':"seg_duration_80_90_min_pct",
                'Segment Duration 90-100 min (percent)':"seg_duration_90_100_min_pct",
                'Segment Duration 100-110 min (percent)':"seg_duration_100_110_min_pct",
                'Segment Duration 110-120 min (percent)':"seg_duration_110_120_min_pct",
                'Segment Duration 120-130 min (percent)':"seg_duration_120_130_min_pct",
                'Segment Duration 130-140 min (percent)':"seg_duration_130_140_min_pct",
                'Segment Duration 140-150 min (percent)':"seg_duration_140_150_min_pct",
                'Segment Duration 150+ min (percent)':"seg_duration_150_plus_min_pct"
            }            